# Base Alpine + OpenRC
#
# base:       /sbin/init as entrypoint
# base-sh:    /bin/sh as entrypoint
# mariadb:    MariaDB server, /sbin/init as entrypoint

version: '2.1'

networks:
  oxyure-net:
    external:
      name: oxyure-net

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        ROOT_PASSWD: ""
        OPERATOR_PASSWD: ""
    image: oxyure:base
    networks:
      oxyure-net:
          ipv4_address: "172.30.0.2"

  base-sh:
    build:
      context: .
      dockerfile: Dockerfile.base-sh
      args:
        ROOT_PASSWD: "testroot"
        OPERATOR_PASSWD: "test"
    image: oxyure:base-sh
    networks:
      oxyure-net:
          ipv4_address: "172.30.0.3"

  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
      args:
        ROOT_PASSWD: ""
        OPERATOR_PASSWD: ""
        MARIADB_ROOT_PASSWD: "test"
    image: oxyure:mariadb
    networks:
      oxyure-net:
          ipv4_address: "172.30.0.4"
