# Build all images in the repository
#
# # Base Alpine + OpenRC # #
#
# base:       * ["/sbin/init"]
# base-sh:    * ["/bin/sh"]
# mariadb:    MariaDB server ["/entrypoint.sh"]
# mini:       Busybox + musl + Tini ["/sbin/tini","/bin/su","-l","-c","/bin/sh","operator"] (no OpenRC, no APK)
#
# # From scrath ##
#
# busybox     Busybox 1.28.0 + Musl 1.1.18 ["/bin/sh"]

version: "3.4"

networks:
  oxyure-net:
    external:
      name: oxyure-net

volumes:
  mariadb-datadir:

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        ROOT_PASSWD: "test"
        OPERATOR_PASSWD: "test"
        http_proxy: "${http_proxy}"
    image: oxyure/base:latest
    networks:
      oxyure-net:
          ipv4_address: "172.30.0.2"

  base-sh:
    build:
      context: .
      dockerfile: Dockerfile.base-sh
      args:
        ROOT_PASSWD: "test"
        OPERATOR_PASSWD: "test"
        http_proxy: "${http_proxy}"
    image: oxyure/base-sh:latest
    stdin_open: true
    tty: true
    networks:
      oxyure-net:
          ipv4_address: "172.30.0.3"

  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
      args:
        ROOT_PASSWD: ""
        OPERATOR_PASSWD: ""
        http_proxy: "${http_proxy}"
    image: oxyure/mariadb:latest
    # An argument is passed to the entrypoint: the MariaDB root password.
    # ! Change it !
    command: ["rootpass"]
    networks:
      oxyure-net:
          ipv4_address: "172.30.0.10"
    ports:
     - 127.0.0.1:13306:3306/tcp
    volumes:
     - mariadb-datadir:/var/lib/mysql

  mini:
    build:
      context: .
      dockerfile: Dockerfile.mini
      args:
        ROOT_PASSWD: "test"
        http_proxy: "${http_proxy}"
    # The image is tagged "latest-full" because the "latest" tag will point to a flattened image
    image: oxyure/mini:latest-full
    networks:
      oxyure-net:
          ipv4_address: "172.30.0.200"

  busybox:
    build:
      context: .
      dockerfile: Dockerfile.busybox
    image: oxyure/busybox:latest
    networks:
      oxyure-net:
          ipv4_address: "172.30.0.210"
